# Generated by Django 4.2.7 on 2023-11-16 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('column', models.CharField(choices=[('todo', 'To Do'), ('in_progress', 'In Progress'), ('done', 'Done'), ('in_review', 'In Review')], default='todo', max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='creation date and time')),
                ('changed', models.DateTimeField(auto_now=True, verbose_name='last changed date and time')),
            ],
        ),
    ]
